#!/bin/bash
set -e

if [ -f /etc/debian_version ]; then
    service apache2 restart
elif [ -f /etc/yum.conf ]; then
    service httpd restart
fi

# Precompile the Horizon assets
cd /opt/stack/horizon
source /opt/stack/venvs/horizon/bin/activate
python manage.py compress
