#!/bin/bash
set -eux

install-packages os-collect-config python-pip build-essential libz-dev libxslt-dev libxml2-dev python-dev

# Minimal static config for bootstrapping
cat > /etc/os-collect-config.conf <<eof
[DEFAULT]
command=os-refresh-config
eof

# Make systemd take notice of it
systemctl daemon-reload

# Enable the service
systemctl enable os-collect-config.service
