#!/bin/bash
set -eu

OK=/opt/stack/boot-stack/init-openstack.ok

if [ -e $OK ] ; then
    exit 0
fi

PATH=/usr/local/bin:$PATH

init-keystone

# after resetting keystone, we must make API services reconnect
#service glance-api restart
#service glance-reg restart
service openstack-nova-api restart

touch $OK
