#!/bin/bash
set -eux

install-packages puppet git python-simplejson

# Install the puppet modules
yum install -y packstack-modules-puppet

mkdir -p /etc/puppet/manifests/
rm -f /etc/puppet/manifests/*
for manifest in $(ls /tmp/in_target.d/manifests/*.pp | sort -r) ; do
  target_manifest=/etc/puppet/manifests/$(basename ${manifest/-*./.})
  if [ ! -e $target_manifest ] ; then
    cp /tmp/in_target.d/common.pp $target_manifest
  fi
  cat $manifest >> $target_manifest
done
cp /tmp/in_target.d/os-config-refresh/52-puppet /opt/stack/os-config-refresh/configure.d/52-puppet

TMPDIR1=$(mktemp -d)
TMPDIR2=$(mktemp -d)
/tmp/in_target.d/bin/swap_binaries /tmp/in_target.d/dummybin $TMPDIR1

# Any of the puppet elements can define a set of rc files to be sourced during install
# and are mainly intended for them to be able to set default facter facts
for rc in $(find /tmp/in_target.d/manifests/ -name "*.rc") ; do
    source $rc
done

# When running puppet inside the chroot, some versions (puppet-3.1.1-5.fc19) need to have these defined
# Todo : Follow up on this
export GEM_PATH=
export LANG=en_GB.UTF-8

# call os-refresh-config with a blank configuration
echo '{}' > /tmp/metadata.json
/opt/stack/os-config-refresh/configure.d/52-puppet /tmp/metadata.json

/tmp/in_target.d/bin/swap_binaries $TMPDIR1 $TMPDIR2
rm -rf $TMPDIR1 $TMPDIR2 /tmp/metadata.json
