#!/bin/bash
set -eux

install-packages puppet git python-simplejson

curl http://repos.fedorapeople.org/repos/openstack/openstack-trunk/fedora-openstack-trunk.repo > /etc/yum.repos.d/fedora-openstack-trunk.repo

mkdir -p /etc/puppet/manifests/
cp -r /tmp/in_target.d/manifests/*.pp /etc/puppet/manifests/
cp /tmp/in_target.d/os-config-refresh/52-puppet /opt/stack/os-config-refresh/configure.d/52-puppet

TMPDIR1=$(mktemp -d)
TMPDIR2=$(mktemp -d)
/tmp/in_target.d/bin/swap_binaries /tmp/in_target.d/dummybin $TMPDIR1

# Any of the puppet elements can define a set of rc files to be sourced during install
# and are mainly intended for them to be able to set default facter facts
for rc in $(find /tmp/in_target.d/manifests/ -name "*.rc") ; do
    source $rc
done

# call os-refresh-config with a blank configuration
echo '{}' > /tmp/metadata.json
/opt/stack/os-config-refresh/configure.d/52-puppet /tmp/metadata.json

/tmp/in_target.d/bin/swap_binaries $TMPDIR1 $TMPDIR2
rm -rf $TMPDIR1 $TMPDIR2 /tmp/metadata.json
