#!/bin/bash
# We need to install this early in install.d because other elements will
# need to use os-refresh-config --print-base to know where to put files

set -eux

install-packages os-refresh-config git-core python-pip

for d in pre-configure.d configure.d migration.d post-configure.d; do
  install -m 0755 -o root -g root -d /opt/stack/os-config-refresh/$d
done
