#!/bin/bash
set -eux

install-packages libapache2-mod-wsgi mariadb-devel
os-svc-install -n horizon -u horizon -r /opt/stack/horizon
# Generate a secret key
echo $(</dev/urandom tr -dc A-Za-z0-9 | head -c 64) > /opt/stack/horizon/openstack_dashboard/local/.secret_key_store
chmod 600 /opt/stack/horizon/openstack_dashboard/local/.secret_key_store
# Horizon uses this for file locks
chown -R horizon:horizon /opt/stack/horizon/openstack_dashboard/local/
